-- SELECT HANGÝ ALANLARI CEKECEGÝMÝZÝ YAZIYORUZ FROM HANGI TABLODAN CEKECEGIMIZI YAZIYORUZ

-- Tüm datayý getirmek için
SELECT * FROM IK_PERSONEL

-- Sadece belirtilen alanlarý getirmek için
SELECT ID_PERSONEL, PERSONEL_ADI , PERSONEL_SOYADI FROM IK_PERSONEL
